server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # يخدم الملفات static طبيعي
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|map)$ {
        try_files $uri =404;
        access_log off;
        expires 1y;
        add_header Cache-Control "public";
    }

    # Angular routes
    location / {
        try_files $uri $uri/ /index.html;
    }
}
