server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # يخدم الملفات لو موجودة
    location / {
        try_files $uri $uri/ @angular;
    }

    # fallback للـ Angular routing فقط
    location @angular {
        rewrite ^ /index.html;
    }
}
